### ISSUE TITLE
cannot touch 'docs/html/.nojekyll': No such file or directory

### ISSUE THREAD

**Issue by virtuosonic** [DenverCoder1/doxygen-github-pages-action#23]
after a push i get this message

```
Run touch docs/html/.nojekyll
touch: cannot touch 'docs/html/.nojekyll': No such file or directory
Error: Process completed with exit code [1](https://github.com/virtuosonic/libcdkpp/actions/runs/5989466679/job/16245682707#step:4:1).
```

This is my workflow file

name: Doxygen GitHub Pages Deploy Action

```
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by DenverCoder1** [comment]
You are overriding the output directory in your doxyfile to a different location than is expected by the workflow.

There are two options you have:

### Option 1 (recommended)

Change line 61 of your Doxyfile to use `docs` as the output directory:

https://github.com/virtuosonic/libcdkpp/blob/e8b51373ea200e0da3e3d636eeb46231be2fae96/Doxyfile#L61

```diff
- OUTPUT_DIRECTORY       =
+ OUTPUT_DIRECTORY       = docs
```


### Option 2

Set the action to expect the output in the current directory's `html` folder instead of inside the `docs` directory that does not exist:

```diff
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
+          folder: html
```
